spring.application.name=ecommerce
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/ecom
spring.datasource.username=ecomuser
spring.datasource.password=ecompassword

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=POSTGRESQL

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
