spring.application.name=config-server
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

#https://github.com/sushantshinde023/job-config-server
spring.cloud.config.server.git.uri=https://github.com/sushantshinde023/job-config-server/