spring.application.name=springsecuritydemo

#Security

spring.security.user.password=abc123
spring.security.user.name=Test

# H2 Database

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
