# ===============================
# = SERVER CONFIG
# ===============================
server.port=8080
spring.application.name=firstjobapp

# ===============================
# = H2 DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# = JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# = LOGGING (SHOW SQL QUERIES)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# = OPTIONAL: PREVENT DB CLOSE
# ===============================
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

# ===============================
# = ACTUATOR
# ===============================
management.endpoints.web.exposure.include=*
#To view more health details
management.endpoint.health.show-details=always
# Info endpoint give information about application like name, version any other details that you want to expose
management.info.env.enabled=true
info.app.name= Job Application
info.app.description= Job app built by sushant
info.app.version=1.0.0

#metrics endpoint - shows application states like jvm memory used, active DB connections, executor pool size, tomcat sessions etc
#loggers endpoint allow us to change login levels at runtime no downtime needed- helpful to debug production issues- you can change this by logger/logger-name api - it will be POST request with configuredLevel:"DEBUG/WARN/INFO" as body
