spring.application.name=producer
server.port=8080

#spring.kafka.bootstrap-servers=localhost:9092
#
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#
## Disable sending Java class metadata in headers
#spring.kafka.producer.properties.spring.json.add.type.headers=false

# Cloud function

spring.cloud.function.definition=uppercase
spring.cloud.function.web.path=/uppercase

# Cloud Stream
spring.cloud.function.definition=sendRiderLocation
spring.cloud.stream.function.definition=sendRiderLocation
spring.cloud.stream.bindings.sendRiderLocation-out-0.destination=rider
spring.cloud.stream.bindings.sendRiderLocation-out-0.content-type=application/json
spring.cloud.stream.binder.brokers=localhost:9092
# If we don't want continues stream we will add delay of 5 seconds
spring.cloud.stream.poller.fixed-delay=5000

